# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Find-Rule-DIZ
version:      0.03
version_from: lib/File/Find/Rule/DIZ.pm
installdirs:  site
requires:
    Archive::Zip:                  0
    File::Find::Rule:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
